[package]
name = "mdbook-frames"
version = "0.1.0"
edition = "2024"
authors = ["Patrick Elsen <pelsen@xfbs.net>"]
license = "MIT"
description = "Preprocessor for mdbook which renders code blocks with window-style frames"

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.8", features = ["derive"] }
env_logger = "0.10.1"
log = "0.4.20"
mdbook-preprocessor = "0.5.2"
pulldown-cmark = "0.13.0"
pulldown-cmark-to-cmark = "21.0.0"
serde = { version = "1.0.192", features = ["derive"] }
serde_json = "1.0.108"
